src/lib/ChargeStation/index.js
If an OCPP server attempts to start a transaction with a valid `idTag`, but the server subsequently rejects the request due to a `ConcurrentTx` status code, surface this as an error to the user.
=> error if startTransaction returns a ConcurrentTx status

src/lib/protocols/ocpp-1.6/index.js
As per section 3.1.2 of Open Charge Point Protocol JSON 1.6, OCPP-J 1.6 Specification (this is equally covered in the 2.0.1 spec too).
=> Specify websocket subprotocol

src/lib/settings.js
This should be `chargePoint` instead of `chargepoint` - https://github.com/e-flux-platform/chargestation/blob/bfa771608e622001b1ce2739bc8bf7a6b69c2547/src/lib/ChargeStation/index.js#L164
=> Ensure chargePointVendor is sent during boot notification

src/lib/ChargeStation/configurations/default-ocpp-201.js, src/lib/ChargeStation/eventHandlers/event-types.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-change-configuration.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-get-configuration.js, src/lib/ChargeStation/eventHandlers/ocpp-201/handle-get-base-report-received.js, src/lib/ChargeStation/eventHandlers/ocpp-201/handle-set-variables.js, src/lib/ChargeStation/index.js, src/lib/ChargeStation/utils.js, src/lib/settings.js, src/screens/Dashboard/SettingsModal.js, src/screens/Dashboard/index.js
Configuration is now a class with common methods for OCPP 2.0.1 and 1.6.
The underlying data structure for those versions is different. For 2.0.1 this is not just a flat array of objects holding just the key values, but is closely modeled after the OCPP spec. (That way we can later do more advanced things like changing the non-Actual variable attributes).
Also added a handler for `SetVariables` message
=> Refactor configuration to support SetVariables

Dockerfile, Dockerfile.dev, buildandpush.sh, package.json, yarn.lock
Issue was closed but latest`favicons` and `favicons-webpack-plugin` don't work together as I see.
https://github.com/jantimon/favicons-webpack-plugin/issues/302
=> Fix for favicons library and bump of Node version.

src/lib/ChargeStation/connection.ts, src/lib/ChargeStation/eventHandlers/ocpp-16/send-status-notification-preparing.js, src/lib/ChargeStation/index.ts, src/screens/Dashboard/StatusNotificationModal.js, src/screens/Dashboard/index.js
=> Some adjustments for status notification.

src/screens/Dashboard/index.js
Some configuration options are conditional based on the model - so when changing the model, we need to get the configuration rebuilt in the same way we do when the protocol changes, otherwise the configuration options aren't visible.
=>  Always rebuild configuration on save  

src/lib/ChargeStation/configurations/e-totem-ocpp-16.ts, src/lib/ChargeStation/configurations/index.js, src/lib/ChargeStation/eventHandlers/ocpp-16/e-totem/handle-session-stopped.ts, src/lib/ChargeStation/eventHandlers/ocpp-16/e-totem/override-session-uid.ts, src/lib/ChargeStation/eventHandlers/ocpp-16/send-stop-transaction.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/send-stop-transaction.ts, src/lib/ChargeStation/index.ts, src/lib/settings.ts, src/screens/Dashboard/SettingsModal.js, src/screens/Dashboard/index.js
- added vendor specific settings, as various bits of behaviour here aren't controlled via OCPP configuration
- code doesn't handle cases where there is either no reply to the price request, or the response is a call error; I generally don't think it's worth covering these cases
- stop time is now stored so this is kept consistent in the cost request
=> Add e-Totem model

src/lib/ChargeStation/configurations/ads-tec-ocpp-16.ts, src/lib/ChargeStation/configurations/default-ocpp-16.ts, src/lib/ChargeStation/configurations/default-ocpp-20.ts, src/lib/ChargeStation/configurations/e-totem-ocpp-16.ts, src/lib/ChargeStation/configurations/sicharge-ocpp-16.ts, src/lib/ChargeStation/eventHandlers/index.ts, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-remote-start-transaction.js, src/lib/ChargeStation/eventHandlers/ocpp-16/send-authorize-or-start-transaction.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-start-transaction.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/send-authorize-or-start-transaction.ts, src/lib/ChargeStation/index.ts, src/lib/settings.ts
- new session option added, `skipAuthorize` - this is currently only set when the session is created via a remote/request start call
- `initiateSession` now invokes `sendAuthorizeOrStartTransaction()` instead of `sendAuthorize()` - the new function pays attention to the configuration value
- configuration option added for 1.6 (already covered for 2.0.1)
=> Respect AuthorizeRemoteStart config option when starting a session

src/lib/ChargeStation/eventHandlers/ocpp-16/handle-remote-start-transaction.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-remote-stop-transaction.js, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-start-transaction.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-stop-transaction.ts
When there is already a session against the connector, a session was always being started for 1.6. The same type of issue also existed for remote stop (both OCPP versions)
=> Fix running session check on remote start

src/lib/ChargeStation/configurations/default-ocpp-16.ts, src/lib/ChargeStation/configurations/default-ocpp-20.ts, src/lib/ChargeStation/eventHandlers/event-types.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-authorize-call-result-received.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-start-transaction-call-result-received.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-stop-transaction-call-result-received.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-token-rejection.js, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-authorize-call-result-received.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-transaction-event-call-result-received.ts
Numerous issues:
- the simulator would continue to charge if `Blocked` status was returned - we now stop if the value is anything but `Accepted`
- the token rejection handler had the condition wrong when checking for an active session on the connector (this fixes a long standing issue where a connector remains unavailable after using an invalid token)
- 2.0.1 side wasn't implementing any event handling around token rejection; instead the status notification write was inlined
=> Fix handling of token rejection for authorize and start transaction

src/lib/settings.ts
As CS suppose to store configuration in strings, setting integer caused an issue:
=> [HW-1352] Fix updating variables for OCPP2.0.1.

src/lib/ChargeStation/index.ts, src/lib/settings.ts, src/screens/Dashboard/SettingsInput.tsx, src/screens/Dashboard/SettingsModal.js, src/screens/Dashboard/StartSessionModal.js
There is currently an issue when numeric values are changed.. e.g. state of charge. These gets passed down to the Session class as string values, and because JS, the handling of these is not correct.
For example with stateOfCharge = `"50"`
```
this.carBatteryStateOfCharge +=
(amountKwhToCharge / this.carBatteryKwh) * 100;
```
can result in a value looking like `"500.103983101"`.
I've extracted out the common input handling elements into a separate component which ensures numeric values are cast before passing to any onChange handlers.
=> Avoid issues with numeric charging station settings

package.json, src/lib/ChargeStation/clock.ts, src/screens/Dashboard/SetDateTimeModal.js, yarn.lock
If your local TZ is not UTC, things get a bit confusing when adjusting the date and time, because the OCPP payloads end up converting the current time to UTC (i.e. it _looks_ different to what you've just set). I think generally it would be simpler if UTC is used everywhere, particularly as the times in tariffs are UTC.
=> Use UTC clock

package.json, src/lib/ChargeStation/clock.ts, src/lib/ChargeStation/connection.ts, src/lib/ChargeStation/queue.ts, yarn.lock
With the dynamic speed controls, setting a speed of e.g. 200x results in time moving forward in multi-minute chunks, yet we have requirements to send e.g. meter values at a lower frequency (configurable, default = 1 minute). So to ensure those are dispatched at the correct interval, this PR adjusts the clock so we move it forward more frequently, with smaller values. Note that the issue will still appear once you get to an even more extreme value, but I think in practical terms we cannot support such cases - and perhaps we should limit the top speed.
I've also replaced the promise queue implementation with one that doesn't require specifying an interval (which should mean no artifical delays in dispatching calls)
=> Tick clock forward more frequently

src/lib/ChargeStation/clock.ts
We recently reduced the interval to 100ms, but this had an unfortunate side-effect in that it seemingly increased the chances of clock skew occurring when speed = 1 (likely because the timing is mildly inprecise, and also browsers throttling invocations for inactive tabs, etc).
I couldn't see a way of competely avoiding this problem from occurring, at least whilst we continue to support the speed up mechanism. So this mitigation just looks to reduce the overall problem. Essentially the frequency of updates to the clock is now proportional to the speed. That means with speed 1, we update the clock once every 1000ms like before. As the speed increases, the clock update frequency increases. We bottom this out at 10 updates / second, because anything lower seems generally undesirable.
=> Reduce chances of clock skew

src/lib/ChargeStation/index.ts
Implemented as per the OCPP 1.6 spec:
> A value of "0" (numeric zero), by convention, is to be interpreted to mean that no sampled data should be transmitted.
=> Support MeterValueSampleInterval of 0

.env, README.md, src/lib/settings.ts, src/utils/env.js
Used `OCPP_BASE_URL` as this alignes with the query param override name (`ocppBaseUrl=...`). Resolves #147
=> Make OCPP backend configurable

src/lib/settings.ts
Not implementing any behaviour around it, for now at least - just supporting the config key. Equivalent OCPP 2 key is already covered.
=> Add ClockAlignedDataInterval configuration key

src/lib/ChargeStation/configurations/default-ocpp-16.ts, src/lib/ChargeStation/configurations/default-ocpp-20.ts, src/lib/ChargeStation/eventHandlers/event-types.js, src/lib/ChargeStation/eventHandlers/ocpp-16/handle-unlock-connector.ts, src/lib/ChargeStation/eventHandlers/ocpp-20/handle-unlock-connector.ts
The original implementation for 1.6 was removed because of an accidental force push.
This PR adds the 1.6 and 2.0 implementation
=> Add unlock connector handlers
