road-labs/chargestation-one

Dockerfile
README.md
buildandpush.bash

This is just a simple script to make deployment a little bit easier. It should be a temporary thing as we seek to improve the deployment process for this simulator. 
- Added a simple script to automate some of the build steps
- Updated README.md
- Specify `platform` to build for in Dockerfile

Add simple build script to make deployment a bit easier

---

src/lib/ChargeStation/clock.ts
src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-start-charging.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-token-rejection.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-transaction-started-ui.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-transaction-stopped-ui.js
src/lib/ChargeStation/eventHandlers/ocpp-16/send-heartbeat-delayed.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/send-meter-values.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/send-stop-transaction.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-get-base-report-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-token-rejection.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-transaction-event-call-result-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-charging-limit-reached.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-heartbeat-delayed.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-start-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-status-notification.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-stop-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-transaction-event-updated.ts
src/lib/ChargeStation/index.ts
src/screens/Dashboard/dashboard.less
src/screens/Dashboard/index.js

This is not 100% covering all the cases, but meter values and heartbeats should fly out 'in the future'
I didn't add 'pause' but that should be easy to do.

Added basic support for "time travel"

---

.github/workflows/merge-master.yaml
Makefile

Build an image and push to Quay on merge to master. There is plenty more we could do CI side - just covering this for now.

Build and push images to Quay

---

src/lib/ChargeStation/eventHandlers/ocpp-16/send-stop-transaction.js
src/lib/ChargeStation/eventHandlers/ocpp-20/send-stop-transaction.ts

Fix issue with tick interval is not set on session.

---

.eslintrc.js
src/lib/ChargeStation/configurations/default-ocpp-16.js
src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-reset.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-set-charging-profile.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-reset.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-set-charging-profile.ts
src/lib/ChargeStation/index.ts
src/screens/Dashboard/index.js

Add stubs to track reset and set charging profile commands.

---

src/lib/ChargeStation/configurations/alpitronic-ccv-ocpp-16.ts
src/lib/ChargeStation/configurations/default-ocpp-16.ts
src/lib/ChargeStation/configurations/index.js
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/index.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/ccv-alpitronic/handle-data-transfer-call-result-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/ccv-alpitronic/send-data-transfer-authorize.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/ccv-alpitronic/send-data-transfer-receipt.ts
src/lib/ChargeStation/index.ts
src/lib/settings.ts
src/screens/Dashboard/StartSessionModal.js
src/screens/Dashboard/index.js

- Adds a CCV Alpitronic specific configuration
- We select the configuration based on the specified ocpp version + model.
- Changed the default model value from `Chargestation v1` to `default`.
- You can now select an authorization type (RFID or CreditCard). 
- In case of Alpitronic, if the authorization type is credit card, the tagId / uid is replaced with the one provided by the CSMS.

Add support for Alpitronic station

---

src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-get-variables.ts
src/lib/settings.ts

[HW-715] Add 'GetVariables' command handler.

---

src/lib/ChargeStation/eventHandlers/ocpp-16/handle-get-configuration.js

This should be all lowercase, as per the spec

Correct readonly field

---

src/lib/ChargeStation/configurations/default-ocpp-16.ts
src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-data-transfer.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-data-transfer.js

Default reply of `UnknownVendorId` since we have nothing further to do with these.

Handle DataTransfer calls

---

src/lib/ChargeStation/eventHandlers/ocpp-16/send-stop-transaction.js

Correct stop transaction payload

---

src/lib/ChargeStation/connection.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/send-status-notification-preparing.js
src/lib/ChargeStation/index.ts
src/screens/Dashboard/StatusNotificationModal.js
src/screens/Dashboard/index.js

This went missing from master somehow.

Some adjustments for status notification.

---

src/lib/ChargeStation/configurations/index.js
src/lib/ChargeStation/configurations/sicharge.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-change-configuration.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/sicharge/generate-session-uid.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/sicharge/handle-data-transfer.ts
src/lib/ChargeStation/index.ts
src/lib/settings.ts
src/screens/Dashboard/index.js

Config option only shows when the model is set appropriately.

Support AdhocPayment vendorId + PaymentCardIdTagPrefix config

---

Dockerfile
package.json
yarn.lock

This reverts commit a2122128fbebf904adf3ca42ca12dabcfeb44d4d.

Revert "Use node 20 and upgrade packages"

---

src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-start-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-stop-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-authorize.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-start-transaction.ts
src/lib/ChargeStation/index.ts

[HW-957] Add remote start/stop on OCPP2.0.1.

[HW-957] Add remote start/stop on OCPP2.0.1.

---

src/lib/ChargeStation/configurations/default-ocpp-16.ts
src/lib/ChargeStation/configurations/default-ocpp-20.ts
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-trigger-message-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/handle-update-firmware-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/send-boot-notification.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-trigger-message-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-update-firmware-received.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-boot-notification.ts
src/lib/ChargeStation/index.ts
src/lib/settings.ts

Implementing `FirmwareUpdate` and `TriggerMessage` handler.
There's also some format automatically changed by prettier

FirmwareUpdate and TriggerMessage handler

---

src/lib/settings.ts

Adding some default keys in configuration of CS.

---

src/lib/ChargeStation/index.ts
src/lib/settings.ts
src/screens/Dashboard/ReplyMessageModal.js
src/screens/Dashboard/SendMessageModal.js
src/screens/Dashboard/dashboard.less
src/screens/Dashboard/index.js

interactive mode

---

src/lib/ChargeStation/index.ts

Adjust charging session log line

---

src/lib/ChargeStation/index.ts
src/screens/Dashboard/index.js

Repeated clicks further increase the speed

Dynamic speed control

---

src/lib/ChargeStation/eventHandlers/ocpp-16/handle-start-charging.js
src/lib/ChargeStation/index.ts
src/screens/Dashboard/SessionStatistic.js
src/screens/Dashboard/SetDateTimeModal.js
src/screens/Dashboard/dashboard.less
src/screens/Dashboard/index.js

- show realtime session statistics
- show session playback speed

Add more visual feedback

---

package.json
src/lib/ChargeStation/clock.ts
src/screens/Dashboard/SetDateTimeModal.js
yarn.lock

Assume local time zone when selecting date and time.
I've added a message that displays the UTC date time as well to inform the user.

Use local timezone

---

src/lib/ChargeStation/eventHandlers/ocpp-16/send-meter-values.ts
src/lib/ChargeStation/eventHandlers/ocpp-16/send-stop-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-start-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-stop-transaction.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/send-transaction-event-updated.ts

This should be EV, as only the EV knows the SoC

Correction to state of charge meter reading location

---

src/lib/ChargeStation/eventHandlers/ocpp-16/handle-remote-stop-transaction.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-request-stop-transaction.ts

[DRI-XXX] Fix transaction ID comparison.

---

package.json
serve/dev.js
yarn.lock

Seemingly the better way to do this is to leverage webpack-dev-server, but it'll be too time consuming to refactor right now. Resolves #145

Open browser on start

---

src/lib/ChargeStation/configurations/default-ocpp-21.ts
src/lib/ChargeStation/configurations/index.js
src/lib/ChargeStation/eventHandlers/event-types.js
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-get-variables.ts
src/lib/ChargeStation/eventHandlers/ocpp-20/handle-set-variables.ts
src/lib/ChargeStation/index.ts
src/lib/settings.ts
src/screens/Dashboard/SettingsModal.js

This just covers what we support for OCPP 2.0.1 for now.

Add basic support for OCPP 2.1
